# Panda demo (ITSE-1003)

Jupyter version of `panda_demo.py`: dictionary → DataFrame, filters, new columns, and quick analysis.

In [4]:
import pandas as pd

## Step 1: build the dataset (dictionary)

In [1]:
data = {
    "name": ["John", "Jane", "Jim", "Jill"],
    "age": [25, 30, 35, 40],
    "major": ["Computer Science", "Mathematics", "Physics", "Chemistry"],
    "gpa": [3.5, 3.8, 4.0, 3.2],
}

## Step 2: original data

In [2]:
print("\nOriginal data set:")
print(data)

Original data set:
{'name': ['John', 'Jane', 'Jim', 'Jill'], 'age': [25, 30, 35, 40], 'major': ['Computer Science', 'Mathematics', 'Physics', 'Chemistry'], 'gpa': [3.5, 3.8, 4.0, 3.2]}

## Steps 3–4: DataFrame

In [5]:
df = pd.DataFrame(data)
print("\nDataFrame:")
df

DataFrame:

   name  age             major  gpa
0  John   25  Computer Science  3.5
1  Jane   30       Mathematics  3.8
2   Jim   35           Physics  4.0
3  Jill   40         Chemistry  3.2

## Question 1: without pandas (age > 20)

In [6]:
print("\nWithout pandas:")
for i in range(len(data["age"])):
    if data["age"][i] > 20:
        print(data["name"][i])

Without pandas:
John
Jane
Jim
Jill

## Question 2: with pandas — oldest student(s)

In [7]:
print("\nWith pandas:")
oldest_student = df[df["age"] == df["age"].max()]
oldest_student

With pandas:

   name  age      major  gpa
3  Jill   40  Chemistry  3.2

## Step 7: new column `grade` (= gpa × 10)

In [8]:
df["grade"] = df["gpa"] * 10
print("\nDataFrame with new column:")
df

DataFrame with new column:

   name  age             major  gpa  grade
0  John   25  Computer Science  3.5   35.0
1  Jane   30       Mathematics  3.8   38.0
2   Jim   35           Physics  4.0   40.0
3  Jill   40         Chemistry  3.2   32.0

## Step 8: boolean column `senior` (age > 20)

In [9]:
df["senior"] = df["age"] > 20
print("\nDataFrame with new column (senior):")
df

DataFrame with new column (senior):

   name  age             major  gpa  grade  senior
0  John   25  Computer Science  3.5   35.0    True
1  Jane   30       Mathematics  3.8   38.0    True
2   Jim   35           Physics  4.0   40.0    True
3  Jill   40         Chemistry  3.2   32.0    True

## Quick analysis: count by major

In [10]:
print("\nQuick Analysis: Count by major?")
df["major"].value_counts()

Quick Analysis: Count by major?

major
Computer Science    1
Mathematics         1
Physics             1
Chemistry           1
Name: count, dtype: int64

## Quick analysis: mean GPA by major

In [11]:
print("\nQuick Analysis: Mean GPA by major?")
df.groupby("major")["gpa"].mean()

Quick Analysis: Mean GPA by major?

major
Chemistry           3.2
Computer Science    3.5
Mathematics         3.8
Physics             4.0
Name: gpa, dtype: float64